### ISSUE TITLE
Report a bug button

### ISSUE THREAD

**Issue by L0Lock** [armadillica/dillo#111]
## Issue

Right now when people have bugs to report, most of them are not aware it's supposed to be here or even don't know what is GIT. So they post on RCS, eventually with the meta tag, and get answered: "it's not here". And there's nowhere easy access to this repo.

And at the end of the day, it becomes a little like said @IIIFGIII on RCS:

> Bureaucracy. Go to the office number 132 and fill out the form number 547... Otherwise nobody will do it.

## Solution
Just a button right in the docker, linking to this repo's issues page. So that users can easily get here.

Mockup:

![xAI14eVWPW](https://user-images.githubusercontent.com/16049822/59492556-81bfb880-8e89-11e9-80f2-6aeb5949db7a.gif)

Maybe it would make sense to make templates, but that's another story.

**Comment by fsiddi** [comment]
Thank you for the suggestion! Will look into this.

**Comment by ChameleonScales** [comment]
I think a bug icon in the bottom-left corner is unlikely going to be noticed or clicked on. Not because of the subtle color but mainly because it's a bit unusual to have it like this.
I suggest a more commonly used question mark ❓ (for Help) on the top-right corner which would unfold a dropdown menu including "Report a bug". It would also make sense to have an "About" in that dropdown which would link to either the [announcement](https://blender.community/c/today/sWbbbc/) or a brand new page to write.

**Comment by IIIFGIII** [comment]
What about something like this. Put all into one menu.

New on picture:
- How To - We need at list minimal howtos. Some page with rules/FAQs. I saw lot of people who don't know how to use markdown and publish their pictures/links correct. Same situation with using search before creating suggestion to not store duplicates. Such page may contain some short text instructions with GIF examples.
- Bug Report - actually link to this Git.
- Donate - Link to donation web page. Pablo reply me on RCS  *We are doing this on our free time and can't afford time to make our own search nor money to cover the expenses. We want to stay away from advertisement on blender.community. Maybe a donation-based or Patreon kind of thing would work for volunteers...*
![1](https://i.imgur.com/7RbTE04.jpg)

**Comment by venomgfx** [comment]
The changes have now been deployed in production.

The new about page contains "how to report a bug" https://blender.community/about
