### ISSUE TITLE
Prevent upload invalid files as thumbnail

### ISSUE THREAD

**Issue by venomgfx** [armadillica/dillo#115]
It's currently possible to upload .blend files as custom thumbnail.

![image](https://user-images.githubusercontent.com/2890874/60514316-85e93400-9cd9-11e9-8f14-ecbe31298b87.png)

**Comment by Sirusdark** [comment]
This file upload is also misleading as it's called "Custom Thumbnail". It actually embeds the uploaded file within the post.

There should be more than one file upload option:
-Thumbnail file upload (aka to have a custom thumbnail instead of a generated one from an attached image)
-File attachments.

**Comment by venomgfx** [comment]
Dillo 4.0 prevents this from happening.

![image](https://user-images.githubusercontent.com/2890874/122293928-d32b3400-cef7-11eb-831e-fd85fcbd5fa9.png)
