### ISSUE TITLE
Bug: HTML-scaling of thumbnails

### ISSUE THREAD

**Issue by Jonta** [armadillica/dillo#133]
Instead of scaling them server-side

Example:

https://blender.community/c/rightclickselect/MSfbbc/

Has thumbnail: https://blender.community/api/storage/file/59/59ee2b501de2fb001513f45c/0e/0ed580788deb41859da7d283b3ab1b69-l.jpg

Which is 1024*576px

In the CSS, .item-thumbnail has the rules "max-height & max-width 90px"

So scrolling through blender.community, our devices load more data than necessary, and for longer than necessary. =)

**Comment by venomgfx** [comment]
The current system to create thumbnails is a bit intensive on the server (which makes the page slow to load because the server is not so beefy), so I chose to re-use the same thumbnail for both small (list) and big (post view) thumbnails, thus making it faster to load the actual post since it only has to create thumbnail once and it's already cached.

Moving to a faster server meant spending more money (Francesco and I pay for Blender Community from our own pockets) while internet speed is usually fast and cheap. 

In Dillo 4.0 we'll try a different thumbnailing process, hopefully using less resources so this would be tackled.

**Comment by venomgfx** [comment]
Solved in Dillo 4.0
