### ISSUE TITLE
404 Not Found when  try to submit proposal on Right-Click Select page

### ISSUE THREAD

**Issue by gakutada** [armadillica/dillo#151]
Any ideas?
cheers
https://blender.community/c/rightclickselect/post/text

**Comment by venomgfx** [comment]
Hi! Thanks for the report.

At the moment and due to the high amount of spam we got lately, posting is disabled for accounts with negative karma points. Your user had negative karma (-5) due to a post of yours being downvoted last year. I've upped your karma now so you should be able to post. 

By the way, in the new version of Blender Community (being released in a matter of weeks!), downvotes on RightClickSelect ideas won't affect karma points. So this won't happen again.
