### ISSUE TITLE
Can't upload gif

### ISSUE THREAD

**Issue by ainex-n** [armadillica/dillo#190]
When Right-Click Select was redesigned, I uploaded a GIF to an existing proposal, but it is not displayed, "Video processing..." status for several months. Same with mp4.
Also the "Delete media" button does not delete files.

**Comment by Lonke** [comment]
I have the exact same issues. MP4s do not load, unable to remove media. Tested on Windows 10 Firefox 94.0.2 and Windows 10 Microsoft Edge 96.0.1054.453. 

Post of mine on rightclickselect where the issues occur: https://blender.community/c/rightclickselect/16vm
mp4 files work fine otherwise:
https://user-images.githubusercontent.com/8409189/145474007-60230cae-4902-4b0f-992e-bc2f10afdd5d.mp4
https://user-images.githubusercontent.com/8409189/145474011-bf16f61b-7750-4612-8224-8095f34dd36b.mp4

**Comment by zenstorm** [comment]
Same issue.  
Loading to this page: https://blender.community/c/rightclickselect/vQzn/
Animated Gifs won't load.  Stuck on: Video processing... 
Size of my gifs were: 
1400 × 1128  @ 434K
1400 × 707  @ 304K
Created in Photoshop 

Attached below: 
![EDIT-BOX-animated](https://user-images.githubusercontent.com/25860174/151512370-27447aac-3c1f-4ecf-af72-722783de462e.gif)

![animated-text](https://user-images.githubusercontent.com/25860174/151512415-4a2b7b0d-fa8f-498f-bcd6-64fca3dcdbc9.gif)

**Comment by ainex-n** [comment]
Hello, @fsiddi, @venomgfx 
- Gif, mp4, etc still cannot be processed.
- Still unable to remove any media in old and new ideas.

<img width="122" alt="Screenshot 2023-02-14 005923" src="https://user-images.githubusercontent.com/25800479/218584151-6e051278-0c65-4b9a-ab59-5f0776a690f7.png">

https://user-images.githubusercontent.com/25800479/218580119-fa30d7f2-d19e-4411-bfb7-a2081b21724b.mp4

**Comment by ainex-n** [comment]
@venomgfx https://blender.community/c/rightclickselect/mpfbbc/

**Comment by venomgfx** [comment]
> @venomgfx https://blender.community/c/rightclickselect/mpfbbc/

Done! :D

**Comment by ainex-n** [comment]
@venomgfx thanks!  :)
