### ISSUE TITLE
Markdown's ordered and unordered lists doesn't work as expected

### ISSUE THREAD

**Issue by antoniobuch** [armadillica/dillo#43]
![image](https://user-images.githubusercontent.com/33925868/33165629-c996caac-d037-11e7-8ace-90d86c8ec89c.png)

In the image you can see that indented ordered lists doesn't work but neither unordered. However, when you're editing your post the result looks right. At the moment of publishing, the format is gone.

**Comment by venomgfx** [comment]
Confirmed. 

The difference is due to the preview using js markdown and the frontend rendering commonmark markdown. 
Links:
* The [broken case](https://blender.community/c/hoy/Fpbbbc/). 
* [Commonmark lists](http://commonmark.org/help/tutorial/10-nestedLists.html)

Thanks for the report! We'll look into it.

**Comment by fsiddi** [comment]
The issue is being discussed on the [Pillar project](https://developer.blender.org/T53817).

**Comment by venomgfx** [comment]
This has been fixed since the switch to CommonMark in Pillar.

@antoniobuch you can test it by giving 3 spaces (not 2) to indent ordered lists.
